server:
  jsp-servlet:
    init-parameters:
      development: true
  context-path: /cmfz
  port: 8989
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  aop:
    proxy-target-class: true
mybatis:
  type-aliases-package: com.syf.entity
  mapper-locations: classpath:com/syf/mapper/*.xml