server:
  jsp-servlet:
    init-parameters:
      development: true
  port: 8989
  context-path: /cmfz
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  type-aliases-package: com.syf.entity
  mapper-locations: classpath:com/syf/mapper/*.xml